version: "3.9"

services:

  # cloudflared:
  #   image: cloudflare/cloudflared
  #   container_name: cloudflare-tunnel
  #   restart: unless-stopped
  #   command: tunnel --no-autoupdate run
  #   environment:
  #     - TUNNEL_TOKEN=$TUNNEL_TOKEN
  #   networks:
  #     - cloudflared

  sqli:
    build:
      context: .
    command: [ "python", "vuln/sqli/vuln_sqli.py" ]
    ports:
      - "1111:1111"
    read_only: true
    tmpfs:
      - /tmp
      - /var/tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    init: true
    restart: unless-stopped
    networks:
      - cloudflared

  xss:
    build:
      context: .
    command: [ "python", "vuln/xss/vuln_xss.py" ]
    ports:
      - "1112:1112"
    read_only: true
    tmpfs:
      - /tmp
      - /var/tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    init: true
    restart: unless-stopped
    networks:
      - cloudflared

  ssti:
    build:
      context: .
    command: [ "python", "vuln/ssti/vuln_ssti.py" ]
    ports:
      - "1113:1113"
    read_only: true
    tmpfs:
      - /tmp
      - /var/tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    init: true
    restart: unless-stopped
    networks:
      - cloudflared

  dvwa:
    image: ghcr.io/digininja/dvwa:eba982f
    container_name: dvwa
    ports:
      - "2111:80"
    restart: unless-stopped

  juice-shop:
    image: bkimminich/juice-shop:v19.1.1
    container_name: juice-shop
    ports:
      - "2112:3000"
    restart: unless-stopped

  webgoat:
    image: webgoat/webgoat:v2025.3
    container_name: webgoat
    ports:
      - "2113:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped


networks:
  cloudflared:
